"""cli

Revision ID: 9637b566923e
Revises: 3c79dd91e18c
Create Date: 2024-01-12 09:49:24.697750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9637b566923e'
down_revision = '3c79dd91e18c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
